server:
  # modify applicationContextPath if you want the root path to be the name of the application
  # for example, set it to /twitter, then the url will become texera.ics.uci.edu:port/twitter
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
